/**
 * app/manifest.ts
 *
 * PURPOSE: Web App Manifest for PWA and SEO.
 * WHY: Improves SEO, enables "Add to Home Screen", better mobile experience.
 *
 * SEO BENEFITS:
 * - Signals to search engines that site is a quality web app
 * - Improves mobile search rankings
 * - Better user experience = lower bounce rate = better rankings
 *
 * URL: /manifest.json (automatically generated by Next.js)
 */

import type { MetadataRoute } from "next";
import { SITE_CONFIG } from "@/lib/constants";

/**
 * Web App Manifest
 * 
 * This file generates /manifest.json automatically.
 * Next.js will serve this at /manifest.json route.
 * 
 * NOTE: Must be async in Next.js 13+
 */
export default async function manifest(): Promise<MetadataRoute.Manifest> {
  return {
    name: SITE_CONFIG.name,
    short_name: "Enlivo",
    description: SITE_CONFIG.description,
    start_url: "/",
    display: "standalone",
    background_color: "#FFFFFF",
    theme_color: SITE_CONFIG.themeColor,
    orientation: "portrait-primary",
    icons: [
      {
        src: "/images/navbar/EnlivotechnologiesLogo.png",
        sizes: "any",
        type: "image/png",
        purpose: "maskable",
      },
      {
        src: "/images/navbar/EnlivotechnologiesLogo.png",
        sizes: "192x192",
        type: "image/png",
        purpose: "any",
      },
      {
        src: "/images/navbar/EnlivotechnologiesLogo.png",
        sizes: "512x512",
        type: "image/png",
        purpose: "any",
      },
    ],
    categories: ["business", "technology", "software"],
    lang: SITE_CONFIG.language,
    dir: "ltr",
  };
}
